apiVersion: v1
kind: Service
metadata:
  name: kitchen-service
  labels:
    app: kitchen-service
spec:
  selector:
    app: kitchen-service
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
