apiVersion: v1
kind: Service
metadata:
  name: kitchen-service-postgres
  labels:
    app: kitchen-service-postgres
spec:
  selector:
    app: kitchen-service-postgres
  ports:
  - port: 5432
    targetPort: 5432
  clusterIP: None
