apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kitchen-service-postgres-pv-claim
spec:
  storageClassName: ""
  volumeName: kitchen-service-postgres-pv
  resources:
    requests:
      storage: 5Gi
  # noinspection KubernetesUnknownValues
  accessModes:
    - ReadWriteOncePod