apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: web-app
spec:
  parentRefs:
    - name: gateway
      sectionName: http
  hostnames:
    - "ciy.localhost"
  rules:
    - backendRefs:
        - name: web-app
          port: 8080