apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  labels:
    app: api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
      - image: ghcr.io/dawidkaluza/cook-it-yourself/api-gateway:develop@sha256:e9e8b6b1996d266d9380ead62a3ae528bc9292d1d56dd4449832ed01b635271c
        name: api-gateway
        envFrom:
          - configMapRef:
              name: gtwy-config
          - secretRef:
              name: gtwy-secrets
        ports:
          - containerPort: 8080