apiVersion: v1
kind: Service
metadata:
  name: api-gateway-redis
  labels:
    app: api-gateway-redis
spec:
  selector:
    app: api-gateway-redis
  ports:
    - port: 6379
      targetPort: 6379
  clusterIP: None
