include:
  - path:
      - compose.common.yml
      - compose.infra.yml

services:
  service:
    build:
      context: .
      dockerfile: Dockerfile.service
    healthcheck:
      test: wget --no-verbose --tries=1 --spider localhost:8080/actuator/health || exit 1
      interval: 2s
      timeout: 5s
      retries: 45
    stdin_open: true
    tty: true
    volumes:
      - ./service/src/:/home/developer/app/service/src/
    networks:
      - main
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy

  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    stdin_open: true
    tty: true
    volumes:
      - ./web/src/:/home/developer/app/web/src/
    networks:
      - main
    ports:
      - "9090:9090"
    depends_on:
      service:
        condition: service_healthy