FROM eclipse-temurin:17.0.11_9-jdk

ARG UNAME=developer
ARG UID=1000
ARG GNAME=developer
ARG GID=1000

RUN groupadd -r -g ${GID} ${GNAME} &&  \
    useradd -l -r -m -u ${UID} -g ${GNAME} ${UNAME}
USER ${UNAME}
WORKDIR /home/${UNAME}/app

COPY --chown=${UNAME} gradle ./gradle
COPY --chown=${UNAME} settings.gradle gradlew ./
COPY --chown=${UNAME} web/build.gradle web/package.json web/package-lock.json ./web/

RUN --mount=type=cache,target=/home/${UNAME}/.gradle,uid=${UID},gid=${GID} \
    --mount=type=cache,target=/home/${UNAME}/app/web/.gradle,uid=${UID},gid=${GID} \
    --mount=type=cache,target=/home/${UNAME}/app/web/node_modules,uid=${UID},gid=${GID} \
    ./gradlew :web:npmCi --no-daemon && \
    cp -R ~/.gradle ~/.gradle_temp && \
    cp -R ~/app/web/.gradle ~/app/web/.gradle_temp && \
    cp -R ~/app/web/node_modules ~/app/web/node_modules_temp

RUN mv ~/.gradle_temp ~/.gradle
RUN mv ~/app/web/.gradle_temp ~/app/web/.gradle
RUN mv ~/app/web/node_modules_temp ~/app/web/node_modules
COPY --chown=${UNAME} web/.env web/.env.production web/index.html ./web/
COPY --chown=${UNAME} web/eslint.config.js web/postcss.config.js web/tailwind.config.js web/vite.config.ts ./web/
COPY --chown=${UNAME} web/tsconfig.json web/tsconfig.app.json web/tsconfig.node.json ./web/

CMD ./gradlew :web:npmDev --no-daemon