apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
  labels:
    app: web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
      - image: ghcr.io/dawidkaluza/cook-it-yourself/web-app:latest
        name: web-app
        envFrom:
          - configMapRef:
              name: web-app-config
        ports:
          - containerPort: 3000