apiVersion: v1
kind: PersistentVolume
metadata:
  name: user-service-postgres-pv
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  # noinspection KubernetesUnknownValues
  accessModes:
    - ReadWriteOncePod
  hostPath:
    path: "/mnt/data"