apiVersion: v1
kind: Service
metadata:
  name: user-service-postgres
  labels:
    app: user-service-postgres
spec:
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: user-service-postgres
  clusterIP: None
