apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: user-service-postgres-pv-claim
spec:
  storageClassName: manual
  resources:
    requests:
      storage: 5Gi
  # noinspection KubernetesUnknownValues
  accessModes:
    - ReadWriteOncePod