apiVersion: v1
kind: Service
metadata:
  name: user-service-redis
  labels:
    app: user-service-redis
spec:
  selector:
    app: user-service-redis
  ports:
    - port: 6379
      targetPort: 6379
  clusterIP: None
