apiVersion: v1
kind: Secret
metadata:
  name: user-service-secrets
data:
  POSTGRES_USER: ZGV2ZWxvcGVy
  POSTGRES_PASSWORD: ZGV2ZWxvcGVy
  RABBITMQ_USER: ZGV2ZWxvcGVy
  RABBITMQ_PASSWORD: ZGV2ZWxvcGVy
  REDIS_PASSWORD: ZGV2ZWxvcGVy
  API_GATEWAY_CLIENT_SECRET: e2JjcnlwdH0kMmEkMTAkWlptNFk5R0w4L1ExWUpNd1NsS2lELlJhRkFQdEJGWFAybElCWGhnMWpPZlBOd1hKR0tiV2U=
