apiVersion: v1
kind: ConfigMap
metadata:
  name: user-service-config
data:
  POSTGRES_HOST: "postgres"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "user"
  POSTGRES_USER: "developer"
  POSTGRES_PASSWORD: "developer"
