apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  labels:
    app: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - image: ghcr.io/dawidkaluza/cook-it-yourself/user-service:latest
        name: user-service
        env:
          - name: POSTGRES_HOST
            valueFrom:
              configMapKeyRef:
                name: user-service-config
                key: POSTGRES_HOST
          - name: POSTGRES_PORT
            valueFrom:
              configMapKeyRef:
                name: user-service-config
                key: POSTGRES_PORT
          - name: POSTGRES_USER
            valueFrom:
              configMapKeyRef:
                name: user-service-config
                key: POSTGRES_USER
          - name: POSTGRES_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: user-service-config
                key: POSTGRES_PASSWORD
          - name: POSTGRES_DB
            valueFrom:
              configMapKeyRef:
                name: user-service-config
                key: POSTGRES_DB
        ports:
          - containerPort: 8080